[package]
name = "linux_process"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
components = { path = "../components" }
posix_x86_64 = { path = "../../arch/posix_x86_64" }
capsules = { path = "../../capsules" }
kernel = { path = "../../kernel" }
linux = { path = "../../chips/linux" }
