[package]
name = "sifive"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
rv32i = { path = "../../arch/rv32i" }
kernel = { path = "../../kernel" }

