# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 20254.

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
  "-C", "link-arg=-Tlayout.ld",
  "-C", "link-arg=-Lboards/nrf52840dk",
  "-C", "relocation-model=static",
]

[build]
target = "thumbv7em-none-eabi"