[package]
name = "earlgrey-cw310"
version.workspace = true
authors.workspace = true
build = "build.rs"
edition.workspace = true

[dependencies]
components = { path = "../../components" }
rv32i = { path = "../../../arch/rv32i" }
kernel = { path = "../../../kernel" }
earlgrey = { path = "../../../chips/earlgrey" }
lowrisc = { path = "../../../chips/lowrisc" }
tock-tbf = { path = "../../../libraries/tock-tbf" }

core-capsules = { path = "../../../capsules/core" }
extra-capsules = { path = "../../../capsules/extra" }


[features]
default = ["fpga_cw310"]

# OpenTitan SoC design can be synthesized or compiled for different targets. A
# target can be a specific FPGA board, an ASIC technology, or a simulation tool.
# Please see: https://docs.opentitan.org/doc/ug/getting_started/ for further
# information.
#
# OpenTitan CPU and possibly other components must be configured appropriately
# for a specific target:
#    - fpga_cw310:
#      OpenTitan SoC design running on CW310 FPGA.
#
#    - sim_verilator:
#      OpenTitan SoC design simulated in Verilator.
fpga_cw310 = ["earlgrey/config_fpga_cw310"]
sim_verilator = ["earlgrey/config_sim_verilator"]
# This is used to indicate that we should include tests that only pass on
# hardware.
hardware_tests = []
