[package]
name = "qemu_rv32_virt_chip"
version.workspace = true
authors.workspace = true
edition = "2018"

[dependencies]
sifive = { path = "../sifive" }
rv32i = { path = "../../arch/rv32i" }
kernel = { path = "../../kernel" }
