[package]
name = "cortexm7"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
kernel = { path = "../../kernel" }
cortexm = { path = "../cortex-m" }
cortex-m-semihosting = "0.3.3"
