sudo: false
language: rust


# bors default configuration:
#branches:
#  only:
#    # This is where pull requests from "bors r+" are built.
#    - staging
#    # This is where pull requests from "bors try" are built.
#    - trying
#    # Uncomment this to enable building pull requests.
#    - master
#
# Instead, I think we just want to disable to bors temp branch
branches:
  except:
    - staging.tmp
    - trying.tmp


cache:
  cargo: true

os:
  - linux

# If you change this, you must also change Getting_Started.md, Makefile.common,
# .vscode/settings.json, and tools/netlify-build.sh.
rust:
  - nightly-2019-09-19

before_script:
  - npm install -g markdown-toc

script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - make ci-travis

