language: rust

os:
  - linux
  - osx

# If you change this, you must also change README and Common.mk
rust:
  - nightly-2015-12-14

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq gcc-arm-embedded; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap px4/px4; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc-arm-none-eabi-49; fi

script:
  - make -C apps/blink TOCK_PLATFORM=storm
  - make -C apps/blink TOCK_PLATFORM=nrf_pca10001

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1ba4725f2c3035cb4966
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
