# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright OxidOS Automotive 2025.

[package]
name = "raspberry_pi_pico_w"
version.workspace = true
authors.workspace = true
build = "../build.rs"
edition.workspace = true

[dependencies]
cortexm0p = { path = "../../arch/cortex-m0p" }
kernel = { path = "../../kernel" }
rp2040 = { path = "../../chips/rp2040" }
components = { path = "../components" }

capsules-core = { path = "../../capsules/core" }
capsules-extra = { path = "../../capsules/extra" }
capsules-system = { path = "../../capsules/system" }
raspberry_pi_pico = { path = "../raspberry_pi_pico" }

# Exports the firmware blobs
tock-firmware-cyw43 = { git = "https://github.com/tock/firmware.git" }

[build-dependencies]
tock_build_scripts = { path = "../build_scripts" }

[lints]
workspace = true
