[package]
name = "nrf52_rubble"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
capsules = { path = "../../../capsules" }
kernel = { path = "../../../kernel" }
nrf52 = { path = "../../../chips/nrf52" }
tock_rubble = { path = "../../components/tock_rubble" }
