[package]
name = "earlgrey"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
lowrisc = { path = "../lowrisc" }
rv32i = { path = "../../arch/rv32i" }
kernel = { path = "../../kernel" }

