[package]
name = "earlgrey"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[features]
# Compiling this crate requires enabling one of these features, otherwise
# the default will be chosen.
config_fpga_nexysvideo = ["config_disable_default"]
config_sim_verilator = ["config_disable_default"]
config_disable_default = []

[dependencies]
lowrisc = { path = "../lowrisc" }
riscv = { path = "../../arch/riscv" }
kernel = { path = "../../kernel" }

