# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2022.
# Copyright (c) 2024 Antmicro <www.antmicro.com>

[package]
name = "veer_el2"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
swerv = { path = "../swerv" }
sifive = { path = "../sifive" }
rv32i = { path = "../../arch/rv32i" }
kernel = { path = "../../kernel" }
lowrisc = { path = "../lowrisc" }
