[package]
name = "tm4c129x"
version = "0.1.0"
authors = ["Alexander MÃ¼llner <es16m017@technikum-wien.at>"]

[dependencies]
cortexm4 = { path = "../../arch/cortex-m4" }
tock_rt0 = { path = "../../libraries/tock-rt0" }
kernel = { path = "../../kernel" }
