# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright OxidOS Automotive SRL 2024
#
# Author: Irina Nita <irina.nita@oxidos.io>
# Author: Darius Jipa <darius.jipa@oxidos.io>

[package]
name = "tock-generator"
version.workspace = true
edition.workspace = true

[dependencies]
prettyplease = "0.2.20"
proc-macro2 = "1.0.82"
quote = "1.0.36"
syn = "2.0.61"
parse = { path = "../parse" }
serde_json = "1.0.116"
clap = { version = "4.1", features = ["derive"] }

# Supported chips
nrf52833 = { path = "../chips/nrf52833" }

