[package]
name = "capsules"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]

[dependencies]
kernel = { path = "../kernel" }
fixedvec = "0.2.3"
msg = { path = "./src/helium/caut" }
