[package]
name = "capsules"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
kernel = { path = "../kernel" }
enum_primitive = { path = "../libraries/enum_primitive" }
cortex-m-semihosting = "0.3.3"