[package]
name = "rv32i"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[features]
riscv64 = ["riscv-csr/riscv64"]

[dependencies]
kernel = { path = "../../kernel" }
tock-rt0 = { path = "../../libraries/tock-rt0" }
tock-registers = { path = "../../libraries/tock-register-interface" }
riscv-csr = { path = "../../libraries/riscv-csr" }

