[package]
name = "stm32f4xx"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
cortexm4 = { path = "../../arch/cortex-m4" }
enum_primitive = { path = "../../libraries/enum_primitive" }
kernel = { path = "../../kernel" }
tock_rt0 = { path = "../../libraries/tock-rt0" }

[features]
default = []

stm32f429zi = []
stm32f446re = []

