[package]
name = "nrf52dk_base"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]


[dependencies]
cortexm4 = { path = "../../../arch/cortex-m4" }
capsules = { path = "../../../capsules" }
kernel = { path = "../../../kernel" }
nrf52 = { path = "../../../chips/nrf52" }
nrf5x = { path = "../../../chips/nrf5x" }
