# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright OxidOS Automotive SRL 2024
#
# Author: Irina Nita <irina.nita@oxidos.io>
# Author: Darius Jipa <darius.jipa@oxidos.io>

[workspace]
members = ["chips/nrf52833", "chips/common", "configurator", "generator", "parse", "parse-macros"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
