# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2024.

[package]
name = "pc"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
kernel = { path = "../../kernel" }
tock-x86 = { path = "../../arch/x86" }
tock-registers = { path = "../../libraries/tock-register-interface" }
tock-cells = { path = "../../libraries/tock-cells" }
# todo: remove external dependency
x86 = "0.51"
