[package]
name = "stm32f429zi"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
cortexm4 = { path = "../../arch/cortex-m4" }
kernel = { path = "../../kernel" }
stm32f4xx = { path = "../stm32f4xx" }
tock_rt0 = { path = "../../libraries/tock-rt0" }
enum_primitive = { path = "../../libraries/enum_primitive" }
