[package]
name = "imxrt1050"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
cortexm7 = { path = "../../arch/cortex-m7" }
cortexm = { path = "../../arch/cortex-m" }
enum_primitive = { path = "../../libraries/enum_primitive" }
kernel = { path = "../../kernel" }
tock-rt0 = { path = "../../libraries/tock-rt0" }

[features]
