[package]
name = "arty_e21_chip"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
sifive = { path = "../sifive" }
riscv = { path = "../../arch/riscv" }
kernel = { path = "../../kernel" }

