[package]
name = "derive-no-peripheral-management"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.12"
quote = "0.4"
