[package]
name = "stm32f401cc"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
cortexm4 = { path = "../../arch/cortex-m4" }
kernel = { path = "../../kernel" }
stm32f4xx = { path = "../stm32f4xx" }
enum_primitive = { path = "../../libraries/enum_primitive" }
