[package]
name = "pico_explorer_base"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
cortexm0p = { path = "../../arch/cortex-m0p" }
capsules = { path = "../../capsules" }
kernel = { path = "../../kernel" }
rp2040 = { path = "../../chips/rp2040" }
components = { path = "../components" }
enum_primitive = { path = "../../libraries/enum_primitive" }

