[package]
name = "swervolf"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
build = "build.rs"
edition = "2021"

[dependencies]
components = { path = "../components" }
rv32i = { path = "../../arch/rv32i" }
capsules = { path = "../../capsules" }
kernel = { path = "../../kernel" }
swervolf-eh1 = { path = "../../chips/swervolf-eh1" }
swerv = { path = "../../chips/swerv" }
